name: Node.js CI

on:
  push:
    branches:
      - testeworkflow
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Configuração do Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' 

      # Instalação de dependências para back_end
      - name: Instalar dependências para back_end
        run: npm install

      # Execução dos testes de unidade e cobertura para back_end
      - name: Executar testes de unidade e cobertura para back_end
        run: npm test
