name: Node.js CI

on:
  push:
    branches:
      - testeworkflow
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Configuração do Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Substitua pela versão correta do Node.js

      # Instalação de dependências para back_end
      - name: Instalar dependências para back_end
        run: |
          cd back_end
          npm install 

      # Executar testes com Jest
      - name: Executar testes com Jest
        working-directory: back_end
        run: npm test
         